/**
 * Semantic Search Type Definitions
 */

/**
 * A code chunk extracted from a file
 */
export interface CodeChunk {
	/** Unique identifier for the chunk (auto-generated by SQLite) */
	id?: number;
	/** File path relative to workspace root */
	filePath: string;
	/** Starting line number (1-based) */
	startLine: number;
	/** Ending line number (1-based) */
	endLine: number;
	/** The actual code content */
	content: string;
	/** Type of chunk (function, class, method, etc.) */
	chunkType: ChunkType;
	/** Name of the symbol (function name, class name, etc.) */
	symbolName?: string;
	/** Language of the file */
	language: string;
	/** Hash of the content for cache invalidation */
	contentHash: string;
}

/**
 * Types of code chunks
 */
export type ChunkType =
	| "function"
	| "class"
	| "method"
	| "interface"
	| "type"
	| "variable"
	| "import"
	| "export"
	| "block"
	| "file";

/**
 * A chunk with its embedding vector
 */
export interface EmbeddedChunk extends CodeChunk {
	/** Embedding vector (768 dimensions for Snowflake Arctic Embed) */
	embedding: number[];
}

/**
 * Search result from semantic search
 */
export interface SearchResult {
	/** The matched chunk */
	chunk: CodeChunk;
	/** Similarity score (0-1, higher is more similar) */
	score: number;
	/** Distance from query (lower is more similar) */
	distance: number;
}

/**
 * Configuration for the semantic search index
 */
export interface IndexConfig {
	/** Path to the SQLite database file */
	dbPath: string;
	/** Dimension of embedding vectors */
	embeddingDimension: number;
	/** Maximum chunk size in lines */
	maxChunkLines: number;
	/** Overlap between chunks in lines */
	chunkOverlap: number;
	/** File patterns to include */
	includePatterns: string[];
	/** File patterns to exclude */
	excludePatterns: string[];
}

/**
 * Index status information
 */
export interface IndexStatus {
	/** Total number of indexed files */
	fileCount: number;
	/** Total number of chunks */
	chunkCount: number;
	/** Last index update time */
	lastUpdated: Date | null;
	/** Whether indexing is currently in progress */
	isIndexing: boolean;
	/** Size of the database in bytes */
	dbSizeBytes: number;
}

/**
 * Embedder interface - abstraction for embedding generation
 */
export interface Embedder {
	/** Generate embedding for a single text */
	embed(text: string): Promise<number[]>;
	/** Generate embeddings for multiple texts (batch) */
	embedBatch(texts: string[]): Promise<number[][]>;
	/** Get the dimension of embeddings */
	dimension: number;
}

/**
 * File change event for incremental indexing
 */
export interface FileChange {
	type: "add" | "change" | "unlink";
	filePath: string;
}
